# Generated by Django 3.1.2 on 2020-10-20 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20201020_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamescore',
            name='second_team',
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='first_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team'),
        ),
    ]
