# Generated by Django 3.1.2 on 2020-10-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20201020_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='second_team',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='first_team',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
