# Generated by Django 3.1.2 on 2020-11-05 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_gamescore_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='first_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_team', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='second_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_team', to='teams.team'),
        ),
    ]
